### ISSUE TITLE
Allow redis 5

### ISSUE THREAD

**Issue by toreym** [chaps-io/gush#101]
Hello, we'd like to use redis gem v5 and have created a PR to gemspec. #100 

We found one test that failed because it was setting a nil key (job.id). We're assuming that this is not possible in normal run time and only required adding id to the test data.

Please review and if you agree that the id should not be nil we'd appreciate merging the PR. 

Thank you!

**Comment by davidbodow-st** [comment]
https://github.com/chaps-io/gush/pull/100 has been merged; should this be closed?
