### ISSUE TITLE
Not able to access Rails project classes in jobs

### ISSUE THREAD

**Issue by jalberto** [chaps-io/gush#16]
Whats the recommended way to run Gush in a Rails (api) project?

I'm trying:

```
APP_PATH = File.expand_path('./config/application', __FILE__)
require_relative './config/boot'
require_relative './config/application'

Dir[Rails.root.join("app/workflows/**/*.rb")].each do |file|
  require file
end
Dir[Rails.root.join("app/jobs/**/*.rb")].each do |file|
  require file
end
```

But is not working properly, every job just fail on start because I'm using clasess of my rails proj in the jobs (like Services or Models).

Stack:
- rails 5 (master) api
- sidekiq 4

Any suggestion?

**Comment by pokonski** [comment]
Can you try the way sidekiq does it:

```ruby
require File.expand_path("#{options[:require]}/config/application.rb")
::Rails::Application.initializer "sidekiq.eager_load" do
::Rails.application.config.eager_load = true
```
?

where `options[:require]` is the path to your app.

**Comment by jalberto** [comment]
Thanks for the suggestion, but I have same result :(

I also tried several variants requiring environment.rb (to your suggestion and to mine) but somethign weird happens then, The jobs are enqueded (I can see after reload it) but the gush workers are not triggered.

This is really blocking me to use gush.

Something I don't understand is, if gush jobs run inside a sidekiq worker, and sidekiq workers are working well, Why this happens?

Thanks in advance

**Comment by jalberto** [comment]
For the record:

I tried to mimic the way binstubs works, bin/bundle, bin/rake, etc. have slight different ways to work, but none worked for me

**Comment by badlamer** [comment]
And  I have same result :(

Rails 4.2.5

**Comment by kakoni** [comment]
This should work with rails >= 4 , adjust those requires accordingly
```
require File.expand_path("./config/application.rb")

::Rails::Application.initializer "gush.eager_load" do
  ::Rails.application.config.eager_load = true
end

require 'sidekiq/rails' #(well piggybagging on this..)
require File.expand_path("./config/environment.rb")
```

**Comment by pokonski** [comment]
Version  1.0 will have an example on how to load Rails projects correctly :)
