### ISSUE TITLE
Logging the jobs

### ISSUE THREAD

**Issue by ferusinfo** [chaps-io/gush#17]
Hey - is there any way to log some things in  jobs/workflow by integrating with Sidekiq logger method? I'd like to save some information while performing the tasks.

**Comment by pokonski** [comment]
You should be able to use the logger by accessing `Sidekiq.logger` inside your jobs.

```ruby
class SomeJob < Gush::Job

   def work
     logger.info "something to log"
   end

  def logger
    Sidekiq.logger
  end
end
```

**Comment by ferusinfo** [comment]
Works like a charm - would you be so nice and add the `logger` property to the Job class itself or should I  make a pull request on this?

**Comment by pokonski** [comment]
Sure, I can add it :+1:

**Comment by ferusinfo** [comment]
Thanks. Great job, by the way!
I've moved from pure Sidekiq to your solution in less than 15 minutes - the only problem I have is the logging and https://github.com/chaps-io/gush/issues/18

**Comment by pokonski** [comment]
Glad to hear it, that was the aim :dancer:

**Comment by ferusinfo** [comment]
I think that this can be closed.
