### ISSUE TITLE
Wrong workflow status after failed jobs

### ISSUE THREAD

**Issue by ferusinfo** [chaps-io/gush#19]
Currently if any jobs will fail (by throwing an exception in a job), the status of the workflow is not properly updated:
- `flow.status` is returning `:running`
- `flow.failed?` is returning `false`

**Comment by pokonski** [comment]
Can you confirm this happens even after reloading the workflow as described here? https://github.com/chaps-io/gush#in-ruby

**Comment by ferusinfo** [comment]
Yes, I can confirm that `flow.reload` isn't changing the status.

**Comment by pokonski** [comment]
Alright, marking as a bug and consulting my :8ball: to find the issue :D

**Comment by ferusinfo** [comment]
Great to hear that, I will try to find it myself as well by reading the source.

**Comment by pokonski** [comment]
@ferusinfo I pushed a fix and a spec for your case. Have a look at master :)

**Comment by ferusinfo** [comment]
I will look into this later - but so far so good! :+1:
