### ISSUE TITLE
Running Workflow Inside of Workflow

### ISSUE THREAD

**Issue by neovintage** [chaps-io/gush#26]
Is it possible to run a workflow inside of a workflow? 

I have a couple of Jobs that run in sequential order but then I have a step where I can fan out to multiple workers. The problem is I don't know the number of workers I need ahead of time in that parallel step and I need to bring them all back together in one step before continuing in the workflow. I've gone through the code and I feel like I'm missing something like a callback to say that a workflow is finished.

**Comment by pokonski** [comment]
Hi, @neovintage!

Right now Gush doesn't have that functionality of nesting workflows. But it's our number one priority on the list of features, as that would be useful also for us internally.

Hackish way at the moment would be making a job that starts a different workflow and polls its status until it finishes (or fails).

**Comment by neovintage** [comment]
I had a feeling that was the case. I wish I had more time to build that functionality in myself. I can't wait to see this enhancement. :-)

Thanks for getting back to me so quickly.

**Comment by hunzinker** [comment]
I have a somewhat related question...

Is it possible for a job to enqueue n number of jobs in a workflow?

Hypothetical example:
```ruby
class Wf < Gush::Workflow
  def configure
    run FindNumbersJob
    run ReduceNumbersJob, after: FindNumbersJob
  end
end

class FindNumbersJob < Gush::Job
  def work
    Numbers.all.each do |num|
      # I'd like to enqueue ProcessNumberJob in the workflow
    end
  end
end

class ProcessNumberJob < Gush::Job
  def work
    # do some really hard work
  end
end
```

**Comment by pokonski** [comment]
@hunzinker you can do that, but not from inside of the Job, but in `configure` method of the workflow, see: https://github.com/chaps-io/gush/issues/24#issuecomment-166703156

**Comment by hunzinker** [comment]
Thanks for the quick reply! I think I'm missing something else. After trying the below, `ReduceNumbersJob` is run after the first `FindNumberJob` finishes which is not desired. Is it possible for `ReduceNumbersJob` to run after all `FindNumberJob`s finish?

```ruby
class Wf < Gush::Workflow
  def configure
    [numbers].each do |n|
      run ProcessNumberJob, params: { position: n }
    end
    run ReduceNumbersJob, after: ProcessNumberJob
  end

```

**Comment by pokonski** [comment]
Each `run` call returns a job `id` you can use for later scheduling, you need a map to get all the ids and the use that array in `after:` attribute:

```ruby
class Wf < Gush::Workflow
  def configure
    process_jobs = [numbers].map do |n|
      run ProcessNumberJob, params: { position: n }
    end
    run ReduceNumbersJob, after: process_jobs
  end
```

**Comment by hunzinker** [comment]
Ha! I just tried that and it worked. Thanks!

**Comment by pokonski** [comment]
Awesome :)

**Comment by pokonski** [comment]
Closing since it was solved a while ago :clock1:

**Comment by kmatrah** [comment]
In the example above, is it possible to use a value from `payloads` for the `numbers` of jobs ?

**Comment by pokonski** [comment]
The number of jobs which will be scheduled is defined at creation time of the workflow. while payloads exist at run time. So you can't schedule jobs when they are already running.

**Comment by kmatrah** [comment]
Thanks for the quick answer!

**Comment by pokonski** [comment]
No problem :)

**Comment by dmitrypol** [comment]
I am building a workflow for data import.  I have DownloadFileJob, ProcessEeachRecordJob and GenerateReportJob.  Since I do not know how many records there will be in each import I am using this pattern:
```
row_jobs = CSV.foreach("path/to/data.csv").map do |row|
  run ProcessEeachRecordJob, params: {row: row}
end
run GenerateReportJob, after: row_jobs
```
I can do `flow = ImportWorkflow.create` and `flow.start!` (kick it off via some process).  However, that will leave the Redis keys after execute.  
I could do this to cleanup:
```
client = Gush::Client.new
client.destroy_workflow flow
```
But how do I execute it after the workflow finishes?  Any suggestions?  Thank you very much.

**Comment by pokonski** [comment]
@dmitrypol this is a good idea. I haven't considered TTL before but overall clean up is something that I think should not be automated - some users might want to leave the workflows, while others might want to remove it right after finishing. 

This could potentially be an option in Gush configuration.

**Comment by Ranjithkumar** [comment]
@pokonski  Nesting workflow enhancement done?

**Comment by ivobenedito** [comment]
Is there any news about supporting nested workflows? This would be super helpful for our project.
