### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by kakoni** [chaps-io/gush#32]
So is scheduling/periodic workflows/jobs something that might be inside gush or should one look into rufus etc to implement it?

**Comment by ferusinfo** [comment]
For scheduling everyday tasks I recommend the https://github.com/tomykaira/clockwork gem.
Gush is a workflow manager, not scheduler, IMHO.

**Comment by pokonski** [comment]
@ferusinfo is right. This is not the scope of Gush. You can use another scheduling tool to execute your Gush workflows :)
