### ISSUE TITLE
Workflow#reload not mutating workflow instance

### ISSUE THREAD

**Issue by originalpete** [chaps-io/gush#37]
I've found either a bug in the code, or a bug in the docs. The README says:

<img width="319" alt="screen shot 2017-05-25 at 14 53 26" src="https://cloud.githubusercontent.com/assets/42993/26465634/f1dbe3a2-4159-11e7-83ec-87e89dda5e70.png">

However, when I try calling `flow.reload`, it doesn't mutate the flow instance status. Instead, I have to run `flow.reload.status` to get an up-to-date status:

```
> flow = MyWorkflow.create
> flow.status
 => :running 
> flow.start!
> flow.reload
> flow.status
=> :running
> flow.reload.status
=> :finished
```

**Comment by pokonski** [comment]
You are right, this could be a good change. Are you willing to submit a PR for this?

**Comment by pokonski** [comment]
@originalpete this is now fixed on the `activejob` branch which will become a 1.0 version very soon. Let me know if you get a chance to test it ou!
