### ISSUE TITLE
Is it possible to set different queue name for each job?

### ISSUE THREAD

**Issue by KirillSuhodolov** [chaps-io/gush#39]

**Comment by pokonski** [comment]
Hey @KirillSuhodolov. I have this planned for the next release `1.1.0` it should be easy to do with ActiveJob since I already assign a queue for all jobs.

**Comment by KirillSuhodolov** [comment]
@pokonski sounds great, do you need any help with it?

**Comment by pokonski** [comment]
Definitely with testing :) So stay tuned!

**Comment by KirillSuhodolov** [comment]
ok, let me know

**Comment by aeris** [comment]
Hi here,

If you are interested, I made a patch for that : https://github.com/aeris/gush/commit/c9f9d9237e53452b1c2b82f509da9a5e51275d7e

**Comment by pokonski** [comment]
@aeris yeah that's exactly how I want to do it :+1:

**Comment by Ranjithkumar** [comment]
@pokonski Can you push this fix as a next version in rubygems?

**Comment by pokonski** [comment]
@Ranjithkumar this is now released under version 2.0.0! Thanks for reminding me :)

Check out other changes here: 
https://github.com/chaps-io/gush/releases/tag/v2.0.0

**Comment by Ranjithkumar** [comment]
Thanks @pokonski
