### ISSUE TITLE
How can I run workflow synchronously(each job with perform_now method)?

### ISSUE THREAD

**Issue by KirillSuhodolov** [chaps-io/gush#40]
Need it for testing and debugging complex workflows in same runtime

**Comment by pokonski** [comment]
Simply set the backend to one the sync backends ActiveJob provides => see the link I added in README http://guides.rubyonrails.org/v4.2/active_job_basics.html#backends

**Comment by KirillSuhodolov** [comment]
and what about, some of them sync and some of them async? Not changing global settings?

**Comment by pokonski** [comment]
You can set it in scope of your spec and revert to original. ActiveJob has one global configuration so it's not Gush specific.

**Comment by pokonski** [comment]
In integration tests for Gush I set the adapter to `:test` https://github.com/chaps-io/gush/blob/master/spec/spec_helper.rb#L6
