### ISSUE TITLE
Is it possible to describe negative behaviour

### ISSUE THREAD

**Issue by KirillSuhodolov** [chaps-io/gush#41]
For example, how to branching workflow and run described job if some job in workflow failed or event workflow failed?

How is it difficult to implement and have it sense? 
Because just rerun failed job not that need. Usually jobs can work with third party services and that services can responded with errors.
At such case when job failed workflow should continue executing due it know how to process such error and even wait for error.

Let me provide synthetic example:

```ruby
class SupplierWorkflow < Gush::Workflow
  def configure()
    run AskSupplierAboutAvailableAmount
    run TryToOrderProducts

    run OrderSuccess, after_success: TryToOrderProducts
    run OrderFail, after_fail: TryToOrderProducts

    # one of them never executes
    run SendMailReport, after_or: [OrderSuccess, OrderFail] 
  end
end
```

may be related issues

https://github.com/chaps-io/gush/issues/18
https://github.com/chaps-io/gush/issues/20

**Comment by pokonski** [comment]
I don't plan on handling failing jobs. The idea is simple, if job fails, the workflow won't continue.

**Comment by KirillSuhodolov** [comment]
Not good idea to run other jobs or workflows inside job. Job should be independent. And workflow describe when, how and execution order.
Workflows looks similar in many parts with saga(process manager) pattern, that can process failed events.

So, I am interesting how you work with such cases, or may be just ignore them?

**Comment by pokonski** [comment]
Yes I ignore them. I consider jobs which fail to be workflow-stopping. It's either all or nothing.

You can use payloads to pass info if the previous job failed and act accordingly. The `OrderSuccess` and `OrderFail` don't have to be separate jobs. They can be separate services running from one job.

**Comment by pokonski** [comment]
Closing as it's answered.
