### ISSUE TITLE
params cast to symbol

### ISSUE THREAD

**Issue by matti** [chaps-io/gush#44]
```
 run MyJob, {
      params: {
        "project_id" => opts["project_id"]
      }
```

--> project_id becomes a symbol, why?

**Comment by pokonski** [comment]
Because they are serialized to JSON, stored in Redis and deserialized from it when job runs.

**Comment by pokonski** [comment]
Happens here https://github.com/chaps-io/gush/blob/master/lib/gush/client.rb#L130. And why a symbol? Pure preference 😁

**Comment by matti** [comment]
huh, if you do a similar thing with sidekiq it keeps keys as strings.

also, if you give a symbol as an argument in sidekiq, it becomes a string. so this behaviour is kinda other way around than in sidekiq.

**Comment by matti** [comment]
https://github.com/chaps-io/gush/blob/master/lib/gush/client.rb#L130

principle of most surprise.

**Comment by pokonski** [comment]
I don't like keys as strings, hence the preference.

**Comment by matti** [comment]
That preference is really against the most popular (?) implementation of similar tool (sidekiq) - it should be atleast configurable

**Comment by pokonski** [comment]
Yeah, configuration option sounds good. Would you mind preparing a PR?
