### ISSUE TITLE
Depend on user input

### ISSUE THREAD

**Issue by benoist** [chaps-io/gush#5]
Hi,

I've had a look at your workflow gem. It looks really clean and neat.
I do have a question about depending on user input. I've got some workflows that require user input in the middle of the flow. Is there any way to specify in the workflow, that an external update is required? 
I understand that this requires me to explicitly push the object in de workflow to the next state after the user input is received.

Cheers,
Benoist

**Comment by pokonski** [comment]
Well, that would be a good way and can be done already in the current state of Gush.

**Comment by stevenharman** [comment]
What about user input to even start the job? e.g., say I wanted to start a whole workflow to publish a book... I'd need to know what book to even publish. How would I pass that into the workflow?

**Comment by pokonski** [comment]
@stevenharman good point. That's what I'm working on now. Passing arguments to workflow, from which you can customize dependencies and pass more arguments down the line. 

Will ping you once I push those changes :)

**Comment by pokonski** [comment]
@stevenharman took a bit, but the workflows with arguments are now on `master` :) 

Check it out and I'd love to hear some feedback :point_right:  https://github.com/pokonski/gush#passing-arguments-to-workflows

**Comment by stevenharman** [comment]
@pokonski Looking good! Thanks!
