### ISSUE TITLE
Gush.configure with namespace issue

### ISSUE THREAD

**Issue by Ranjithkumar** [chaps-io/gush#62]
In the Gush.configure, If we add namespace XXX then sidekiq is not pulling the jobs.

If we add namespace as "gush" then its pulling the job.

**Comment by pokonski** [comment]
You have to tell side which queues to use explicitly, so if you specify `xxx` as namespace/job queue you have to run sidekiq with that queue:

```
bundle exec sidekiq -q xxx -q some_other_queue```

**Comment by Ranjithkumar** [comment]
@pokonski I guess there are some confusion. Please check my attachment 
![gush 2018 11 23 12 32 38](https://user-images.githubusercontent.com/116991/48931569-057d7c00-ef1d-11e8-8ee9-689c235cd9e2.png)

Gush::Client takes default namespace as '**gush**'. 
For Jobs, I am using queue name as '**rans**'.
I am running sidekiq using **sidekiq -C config/sidekiq.yml** It has all the queue information. Its working fine with this config.

If I change the Gush::Client namespace to '**gush_dev**' then its not processing the jobs.

**Comment by Ranjithkumar** [comment]
@pokonski  Its working fine with version 2.0.0!
