### ISSUE TITLE
bundle exec viz workflow with parameters

### ISSUE THREAD

**Issue by lefterisnik** [chaps-io/gush#64]
How can I run `viz` for a workflow with parameters?

When I try to run `viz` I am getting:
```
ArgumentError: wrong number of arguments (given 0, expected 1)
```

My workflow is: 
```
class AssessmentWorkflow < Gush::Workflow
  def configure(assessment_id)
    run Job1, params: {assessment_id: assessment_id}
    run Job2, params: {assessment_id: assessment_id}, after: Job1
    run Job3, params: {assessment_id: assessment_id}, after: Job2
  end
end
```

**Comment by pokonski** [comment]
Hey, this is not currently possible from the command line.

To do it the command would have to accept parameters as JSON, the same way actual workflows get it.

**Comment by lefterisnik** [comment]
Thanks @pokonski  for your answer. Could you provide an example?

**Comment by pokonski** [comment]
You could do it manually inside your app via:

```ruby
      workflow = AssessmentWorkflow.new(some_argument)
      graph = Gush::Graph.new(workflow)
      graph.viz
      Launchy.open graph.path
```

**Comment by lefterisnik** [comment]
Thanks @pokonski

**Comment by rajaravivarma-r** [comment]
@lefterisnik I encountered the same problem and I just set a default argument temporarily for it to work. Though, it would be useful for someone.
```ruby
class Workflow < Gush::Workflow
  def configure(argument = 'default temporary') # Temp argument here
    ...
  end
end
```
