### ISSUE TITLE
Cannot assign requested address - connect(2) for [::1]:6379

### ISSUE THREAD

**Issue by chrisvel** [chaps-io/gush#67]
I added Gush in a Rails app along with Sidekiq. 

I have added the Gushfile and the 'gush' queue to the sidekiq.yml. When I try to start a workflow I am getting strange Redis errors:

```
Errno::EADDRNOTAVAIL in NetworksController#create

Cannot assign requested address - connect(2) for [::1]:6379
```

I know I am missing something but what?

**Comment by pokonski** [comment]
Looks like your app can't connect to Redis, did you configure it?

**Comment by chrisvel** [comment]
This is an app I've been working successfully for months. Something changed with the installation of the gem and I can't figure out what. I need to mention that I am using Rails/Sidekiq/Postgres/Redis in docker containers with docker-compose.

**Comment by pokonski** [comment]
Did you update the gem? What version are you using? I can't really help with fixing bugs in your own app that is unrelated to the gem. How do you configure Redis? It seems it tries to use ipv6, is it expected?

**Comment by chrisvel** [comment]
In Sidekiq `config.redis = { url: (ENV["REDIS_URL"] || 'redis://localhost:6379/1') }` and in docker-compose `REDIS_URL: 'redis://redis:6379/1'`. The thing is that If I uninstall the gem, sidekiq jobs function just fine.

**Comment by pokonski** [comment]
What does your gushfile look like?

**Comment by chrisvel** [comment]
```
require_relative './config/environment.rb'
config.autoload_paths += ["#{Rails.root}/app/jobs", "#{Rails.root}/app/workflows"]
```

**Comment by pokonski** [comment]
This is incorrect, the config.autoload_paths does not go into Gushfile, please check this section again carefully: https://github.com/chaps-io/gush#ruby-on-rails

**Comment by chrisvel** [comment]
That was a foolish thing to do :( 
Restarted the rails server but I don't see any change. I guess the Gushfile has to go in the Rails root along with the Gemfile etc.

**Comment by pokonski** [comment]
Alright, so please try configuring redis url directly for Gush like described here:

https://github.com/chaps-io/gush#cleaning-up-afterwards

(basically, create a new initializer with:


```ruby
Gush.configure do |config|
  config.redis_url = ENV["REDIS_URL"] || 'redis://localhost:6379/1'
end
```

**Comment by chrisvel** [comment]
It works. I see you hardcoded the redis hostname to localhost ?

**Comment by pokonski** [comment]
The `ENV["REDIS_URL"] || 'redis://localhost:6379/1'` comes from your snippet above. But yeah localhost is a fallback if you don't provide your own.

https://github.com/chaps-io/gush/blob/master/lib/gush/configuration.rb#L12

**Comment by chrisvel** [comment]
I haven't read the cleanup section to be honest. We may update the readme with adding the initialiser to the top If you agree. Thanks for helping.
