### ISSUE TITLE
Overlapping workflows

### ISSUE THREAD

**Issue by anirbanmu** [chaps-io/gush#68]
I am confused about this section of the README: https://github.com/chaps-io/gush#avoid-overlapping-workflows

Can someone please explain why I should "avoid starting the next scheduled workflow iteration while the current one with same class is still running."? What I'm looking into using gush for explicitly would require having multiple iterations of the same workflow (albeit with different parameters) running concurrently. Is this a problem for gush? Are there some internal assumptions that break if there are multiple versions of a workflow in flight at once?

**Comment by pokonski** [comment]
This is a suggestion, not something Gush prevents. It's a snippet you can implement if you only want one workflow of the same type to run
