### ISSUE TITLE
Update Gem on RubyGems

### ISSUE THREAD

**Issue by jatindhankhar** [chaps-io/gush#77]
The recent commit (https://github.com/chaps-io/gush/commit/609f19d47042a37c33d21997d1cde8947ab021c0) bumped the activejob dependency which allows it to work with rails 6+. 

However this commit is not present on the latest gem available RubyGems.
 This throws dependency issue with activejob while using the gem directly from rubygems. 

`gem 'gush', '~> 2.0', '>= 2.0.1'`

Workaround is to specify the git commit 

`gem 'gush', github: 'chaps-io/gush', ref: '609f19d47042a37c33d21997d1cde8947ab021c0'`

Please update the gem on rubygems :) 

![Screenshot 2020-03-17 at 3 34 10 PM](https://user-images.githubusercontent.com/2412081/76845365-c509e600-6864-11ea-91e1-45af229eee2d.png)

cc - @pokonski

**Comment by katzj** [comment]
Any chance of getting an updated gem pushed here?

**Comment by kbarrette** [comment]
@pokonski any news on a release for this?

**Comment by pokonski** [comment]
2.0.2 is released, apologies for the massive delay!
