### ISSUE TITLE
Detailed job status?

### ISSUE THREAD

**Issue by xtagon** [chaps-io/gush#8]
Hi,

I use Sidekiq workers already, but Gush appeals to me because Sidekiq doesn't have a way to define such workflows/dependencies. Since Gush "just uses Sidekiq" is it compatible with Sidekiq plugins? Specifically, I would like a way to track progress/status of jobs. Let's say I have a job that is going to process 100 files, I would like to be able to add logic into my process method to count how many files have been done at any given moment, and store it in Redis so that I can query it while the job or workflow runs.

For some tasks, this will mean keeping track of the progress of a number of serial/parallel jobs, for others I want progress of an individual job. Is there a way to do this with Gush, if not, could it be planned for the future?

Thanks for listening,
Justin

**Comment by pokonski** [comment]
Hi, Justin.

Do you have any particular plugin on your mind? We could always test it :)

**Comment by xtagon** [comment]
[sidekiq-status](https://github.com/utgarda/sidekiq-status) has almost all of the features I would need. I'll try to test it with Gush next week.

**Comment by pokonski** [comment]
For anyone interested, there's https://github.com/chaps-io/gush-control which adds `gush server` command that runs Web UI with details about running and finished workflows :)
