### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by kzkn** [chaps-io/gush#82]
Hi maintainers , I've noticed this project and found it extremely useful, but also noticed there haven't been any new releases since March last year and no commits since February.

So it got me wondering whether including it in new project is a sensible idea:

-    Is this project being actively maintained?
-    Is there plan to continue to maintain this project in the future?
-    Is there a roadmap?

Thanks!

**Comment by mollerhoj** [comment]
Hi, just found this. I need the features, but wondering the same thing. Does anyone know of alternative gems?😊

**Comment by joshRpowell** [comment]
this was recently presented at RubyConf 2021 https://github.com/fractaledmind/acidic_job

**Comment by mollerhoj** [comment]
@joshRpowell Do you know if that talk available anywhere? Will it be made available?

**Comment by pokonski** [comment]
If anyone feels like being a maintainer and has ideas about further improvements, let me know!

**Comment by joshRpowell** [comment]
@pokonski there is a lot of activity in the network https://github.com/chaps-io/gush/network

We're in the process of upgrading to Rails 7 and need to make some additional changes. 

Would love to volunteer to be added as a maintainer and collaborate with others to move the project forward. 

cc: @kzkn @shaul75 @pushtech @manhcuongdtbk

**Comment by pokonski** [comment]
Hey, Josh! Thank you for the very kind offer, I'm not opposed to it :) 

I will try to be more pro-active now with reviewing your contributions so please keep them going! If that works out I think we can move forward with giving write permissions and later possibly publishing permissions on Rubygems

PS. I had messed up Github notifications settings months ago, that's why I missed so much of activity here :sweat:

**Comment by pokonski** [comment]
New version 2.1.0 is out with Rails 7.0 support! Thanks again for the help to everyone involved :boom:

**Comment by kzkn** [comment]
I am happy to see that maintenance of this library has resumed :grinning: I close this issue. Thanks for maintainers!
