### ISSUE TITLE
Project Idea - Web UI

### ISSUE THREAD

**Issue by shaul75** [chaps-io/gush#91]
One of the difficulties we face when running complex workflows is monitoring them in real-time, seeing the whole picture per specific executions and/or investigating what went wrong.

These are some of my thoughts on the capabilities:
- List all workflow executions in a table with timestamps and a status
- Monitor individual execution:
   - Interactive graph with colors indicating job statuses (red failure, green success etc.)
   - Display useful information about jobs (duration, input/output, logs)
   - Ability to do ad-hoc operations with individual jobs within a running workflow - place it "On Hold", "Mark as Success", "Cancel" etc.

I started fiddling around a bit on creating a dependency manager + Admin UI before I came across this gem. I'm curious would this be a feature desired as an enhancement for Gush?

**Comment by pokonski** [comment]
There is one but it is admittedly very old https://github.com/chaps-io/gush-control
