### ISSUE TITLE
cannot create workflow instance

### ISSUE THREAD

**Issue by shuheix** [chaps-io/gush#92]
Hi, I try to create workflow instance at rails console, but i cant

its never ends
![image](https://user-images.githubusercontent.com/68313834/185301626-e7a96402-2ceb-4b76-9304-6ee8de342521.png)

gush 2.0.1
```ruby
# app/workflows/sample_workflow.rb
class SampleWorkflow < Gush::Workflow
  def configure
    run SleepJob
  end
end
```
```ruby
# app/jobs/sleep_job.rb
class SleepJob < Gush::Job
  def perform
    logger.debug("start")
    sleep(30)
    logger.debug("end")
  end
end
```
```ruby
# Gushfile
require_relative './config/environment.rb'
```
```ruby
# application.rb
config.autoload_paths += %W[#{config.root}/lib #{Rails.root}/app/workflows #{Rails.root}/app/jobs]
```
sorry, what should I check?

**Comment by pokonski** [comment]
Creating workflows requires working Redis connection, it seems it is not properly working for you. Check if Redis is running and you can connect to it from your app, first.

**Comment by shuheix** [comment]
thanks you for your answer
I try to check redis connection
